### ISSUE TITLE
Returning reference from cometa::function results in compile error on Windows/Clang/LLVM.

### ISSUE THREAD

**Issue by degski** [kfrlib/cometa#1]
When returning a reference type from `cometa::function<something & (some parameters...)>` on Windows VC14/Update3 with Clang/LLVM (http://llvm.org/builds/) a compiler error is raised. Returning a pointer `cometa::function<something * (some parameters...)>` works fine, and is obviously a work-around, but it would be nice to have a reference returned. 

edited: clarify what I intended to say.

**Comment by dancasarin** [comment]
Fixed in 84b4972.
The previous implementation returned default-constructed value of the `Return` type if an empty function was being called.
But because the reference types haven't empty value, now segfault (Access violation) will be raised at runtime if an empty function is called. Enclose the call in an if-statement to prevent segfault.
Thanks.

**Comment by degski** [comment]
Fixed indeed, thanks...
